{{- $orderflowLabels := include "orderflow.labels" . -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Values.app.instance }}-{{ .Values.app.installation }}-hpa'
  labels:
    {{- $orderflowLabels | nindent 4 }}
#  annotations:
#    "helm.sh/hook": "post-install"
#    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ .Values.app.instance }}-{{ .Values.app.installation }}'
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_http_requests
      target:
        type: AverageValue
        averageValue: 1000