{{- $orderflowLabels := include "orderflow.labels" . -}}
{{- $orderflowSelectors := include "orderflow.selectors" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.app.instance }}'
  labels:
    {{- $orderflowLabels | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: '{{ .Values.aws.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.aws.AWS_SECRET_ACCESS_KEY }}'
