{{- $orderflowLabels := include "orderflow.labels" . -}}
{{- $orderflowSelectors := include "orderflow.selectors" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.app.instance }}'
  labels:
    {{- $orderflowLabels | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVNFNUtRM0YySlU3VVJQNFQ=
  AWS_SECRET_ACCESS_KEY: c0lrYlZiNndTU2crUWMyWU5yMkswR0FocGRRUGwraE54TnVTMGpRNQ==
