{{- $orderflowLabels := include "orderflow.labels" . -}}
{{- $orderflowSelectors := include "orderflow.selectors" . -}}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.app.instance }}'
  labels:
    {{- $orderflowLabels | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: '{{ .Values.service.type }}'
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    {{- $orderflowSelectors | nindent 4 }}
